#-------------------------------------------------------------------------------
#--- A string is simply an ordered collection of symbols selected from 
#--- some alphabet and formed into a word; the length of a string is the number of symbols 
#--- that it contains. An example of a length 21 DNA string (whose alphabet contains the 
#--- symbols 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."
#--- Given: A DNA string s of length at most 1000 nt (nucleotides).
#--- Return: Four integers (separated by spaces) counting the respective number of times 
#--- that the symbols 'A', 'C', 'G', and 'T' occur in s.
#--- 
#--- Code written by: Edgar Garriga				edgargarriga.com
#-------------------------------------------------------------------------------
#we define the function , we have the string SEQ as paramether
def countSymbol (seq):
        seq.upper() #all the string to upperCase letters
        print "{} {} {} {}".format(seq.count('A'),seq.count('C'),seq.count('G'),seq.count('T'))

s = "TGCTCCGCGTTAGCTTTGTATGAATACCGGCGTATGGGGCCGACACCTACCTAACCACTTAACAGAAATGAAGGGTCGAAGAATGGTTGCAGCGGTAACCGTCCTAAATCAACCTTCGGGTCATGCAACAAACTATACACTTGCTAGTATATATTAGGCGACAGCTTTCTCATTAGGAGATATTCGCGGCAGACCCTGTTCTCAGCAACTCTCCTGGAAATTAACAAACCCGTAGATCGCAAGTCTGCGTGTACGTATGTAATAATGGGTCCCGTACAACGACAGACTGCATGGAGTGATCTGGCCTGATGCCCTGAGCGTGTCTCGGCGAAAGCCGTAGACCACAGCGGCTTGAAACTACCGAATCCGTAGCGGCTGCGATCACTTTCGAAGACTAGGCCCGGGTTTGATGACGTCGTCACAGACTATACACGCTGAAAGTTCCTTTCGCATCCCATGGGGAATTAGACACATCTCGTGTCGTATGTCTTCACCATCGTTTAGTCCGCCGAGAGATTAGCGCATGCAGTGCGCAGCATCAGGGTCACGTAGTAGATTACGACAGCGCTTCGTCTATTGAGCACGTAGGTACCATGAAATTTTGCTTGAAATAATAGCGACGTGGAAGAAAAACCTGTGCGGACTGATAATGCGGGGCTAACAGTGGAAACTGGACTTTGCGGTGTTACAGTCCCCGCATGCCCCATGTGAGCACGGATCGAAATTTATTCTAGGCTGAGAGAGGCCGGACTTTGCGGCCCGTATGCATAAAGCGGTATGGCTCGAAGAGGACACGCGCTCACCAGACCCCAAAACAGCTGATGCATTCGACAAGCGCGATTAGCAACCCTCGACATACACCGTGTCTGGAGGAATCACCTTCCGAGCAACTAACACATGAGAAGGCCTCTCACCGTGTGCAAGGGACGCTCAACAGATAGGGGCACCTCCACTATTTCCAGCCAGCTAAGCT"
countSymbol(s)
