#-------------------------------------------------------------------------------
#--- Write a Python function named decode() that decodes a RNA string into the protein it
#--- encodes(look at http://rosalind.info/problems/prot/ for help and for examples)
#--- Given: An RNA string s corresponding to a strand of mRNA (of length at most 10 kbp).
#--- Return: The protein string encoded by s.
#--- Code written by: Edgar Garriga				edgargarriga.com
seq = "ACAGTTAATAGTTAATGGCGGAGTTAATCTTTAGTTAATGAGTTAATGAGTTAATCCGATGAGTTAATAAAGTTAATAAAGTTAATATAGAAGTTAATTGTTCTAGTTAATAGTTAATAGTTAATAGTTAATGGGTAGTTAATGATTTCCGCAGTTAATAGTTAATCGCAGATGCAGTTAATCATACGTAGTTAATACTTAGTTAATGAGAGTTAATAGTTAATGAGTTAATACAAGTTAATAGTTAATAAGAGTTAATAAGTTAATTTAAGTTAATAGTTAATAGTTAATTATGCCAGTTAATAAGTTAATAGTTAATCGCTAGTTAATCGGAGTTAATGAAGTTAATGGTGGAAGGTTACTCGGGCCCCTTAGTTAATACTAGTTAATCAGTTAATATAGTTAATGATAGTTAATCCGCAAGTTAATAAGTTAATTAGTTAATAGTTAATTAAGTTAATTAGTTAATCAGTTAATATACACAGTTAATAGTTAATAGTTAATAAGTTAATTAGTTAATTTACTAGTTAATCAGTTAATCTTGTAGAAGTTAATAGTTAATTCAGTTAATTAGTTAATGAGTTAATCAGTTAATCGAGTTAATGACGACAGTTAATGGGAAGTTAATCAGTTAATAGTTAATTAGTTAATTCAATACAGTTAATAGTTAATCTGAGTTAATAGTTAATCAGTTAATCAAGTTAATAAGTTAATGTAGTTAATAGTTAATGTTAGTTAATGTAAGTTAATCAGTTAATGAGTTAATCCAGTTAATAGTTAATAGTTAATAGTTAATACAGTTAATAAAGTTAATCCACACTCAGTTAATTAGTTAATAGTTAATGTCAGTTAATATTGTGGGAGTTAATAAGTTAATCAGTTAATTGTGCGAATAGTTAATAGTTAATCGAGTTAATTGAGTTAATAAGGTAATGCTAGTTAATTGAGTTAATGAGTTAATAAT"
subs ="AGTTAATAG" 

# Start with this value.
location = -1

# Loop while true.
while True:
    # Advance location by 1.
    location = seq.find(subs, location + 1)

    # Break if not found.
    if location == -1: break

    # Display result.
    print(location+1)